### ISSUE TITLE
possible point for verification

### ISSUE THREAD

**Issue by DhavalRepo18** [cod3licious/autofeat#21]
https://numpy.org/doc/stable/reference/generated/numpy.exp.html

A review needed?  or comment is needed?

https://github.com/cod3licious/autofeat/blob/master/autofeat/feateng.py#L151
https://github.com/cod3licious/autofeat/blob/master/autofeat/feateng.py#L166

**Comment by cod3licious** [comment]
Thanks for flagging this. Indeed this is one of those cases where you wish your past self had noted a reason for why this was done this way and not just an oversight. But since this is only done for the unit-transformations I think this was actually done on purpose since the library doesn't want something like 2^kg but it is fine with exp(kg) so since for these purposes the two are equivalent (since you're not computing the actual values) it's not an error.

**Comment by DhavalRepo18** [comment]
@cod3licious but then, is there any placer where for unit based calculation, two engineered columns become identical for let say same features?

**Comment by cod3licious** [comment]
@DhavalRepo18 no, this check is just to confirm whether doing this computation with a feature of a certain unit is a legal operation or not, it doesn't affect the actual value of the feature after the computation
