### ISSUE TITLE
Cython implementation

### ISSUE THREAD

**Issue by fkhan00** [cod3licious/autofeat#4]
I was thinking of using cython to run autofeat in C and changing some of the variables to static.  Do you think this would make autofeat significantly faster?

**Comment by cod3licious** [comment]
Hey @fkhan00 : the main bottleneck is the feature generation using the sympy library (which computes the different feature formulas to make sure there are no redundant features being generated etc.). Since it's probably not possible to improve a lot there with cython, I'm not sure if you'll really get a huge performance boost. But if you try it and it helps, I'd be happy about a pull request! :) good luck!

**Comment by Sandy4321** [comment]
better without cython pls, since it is usually problem  to install code based on cython
thanks
